export const cartActionTypes = {
    CART_VISIBILITY: 'CART_VISIBILITY',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    REMOVE_CART_ITEM_QUANTITY: 'REMOVE_CART_ITEM_QUANTITY'
};